export const READ_ONE_CUSTOMER = "READ_ONE_CUSTOMER";
export const READ_CUSTOMER_SOURCES = "READ_CUSTOMER_SOURCES";
export const CUSTOMER_DETAIL_ERROR = "CUSTOMER_DETAIL_ERROR";
export const CLEAR_CUSTOMER_DETAIL = "CLEAR_CUSTOMER_DETAIL";
