export const READ_CUSTOMERS = "READ_CUSTOMERS";
export const CUSTOMER_ERROR = "CUSTOMER_ERROR";
export const CLEAR_CUSTOMERS = "CLEAR_CUSTOMERS";
export const START_CUSTOMER_RELOAD = "START_CUSTOMER_RELOAD";
export const FINISHED_CUSTOMER_RELOAD = "FINISHED_CUSTOMER_RELOAD";
