export const READ_CUSTOMER_EVENTS = "READ_CUSTOMER_EVENTS";
export const CUSTOMER_EVENT_ERROR = "CUSTOMER_EVENT_ERROR";
export const CLEAR_CUSTOMER_EVENTS = "CLEAR_CUSTOMER_EVENTS";
export const START_CUSTOMER_EVENTS_RELOAD = "START_CUSTOMER_EVENTS_RELOAD";
export const FINISHED_CUSTOMER_EVENTS_RELOAD =
  "FINISHED_CUSTOMER_EVENTS_RELOAD";
