export const READ_CUSTOMERS = "READ_CUSTOMERS";
export const READ_ONE_CUSTOMER = "READ_ONE_CUSTOMER";
export const CUSTOMER_ERROR = "CUSTOMER_ERROR";
export const CLEAR_CUSTOMERS = "CLEAR_CUSTOMERS";
export const START_CUSTOMERS_RELOAD = "START_CUSTOMERS_RELOAD";
export const FINISHED_CUSTOMERS_RELOAD = "FINISHED_CUSTOMERS_RELOAD";
