export const READ_EVENTS = "READ_EVENTS";
export const EVENT_ERROR = "EVENT_ERROR";
export const CLEAR_EVENTS = "CLEAR_EVENTS";
export const START_EVENTS_RELOAD = "START_EVENTS_RELOAD";
export const FINISHED_EVENTS_RELOAD = "FINISHED_EVENTS_RELOAD";
