export const READ_SOURCES = "READ_SOURCES";
export const SOURCE_ERROR = "SOURCE_ERROR";
export const CLEAR_SOURCES = "CLEAR_SOURCES";
export const START_SOURCES_RELOAD = "START_SOURCES_RELOAD";
export const FINISHED_SOURCES_RELOAD = "FINISHED_SOURCES_RELOAD";
